[phases.setup]
nixPkgs = ["gcc", "postgresql_16", "python39"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python -m gunicorn.app.wsgiapp main.wsgi:application --bind=0.0.0.0:8080"

[variables]
DJANGO_SETTINGS_MODULE = "main.settings"
