[phases.setup]
nixPkgs = ["gcc", "postgresql_16", "python39"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn main.wsgi:application"
